-- Peztz production-domain migration for existing PostgreSQL tables.
--
-- Apply this file before deploying the Spring Boot domain API build.
-- It reuses existing production tables and only adds what the Spring API
-- needs for authentication tokens and generated numeric IDs.

begin;

-- Fail before making changes when this is run against an empty database or
-- an unexpected schema. This migration is only for the existing Peztz schema.
do $$
declare
    missing_tables text;
begin
    select string_agg(required_table, ', ' order by required_table)
    into missing_tables
    from unnest(array[
        'public.users',
        'public.hospitals',
        'public.cage',
        'public.access_session',
        'public.pet_logs'
    ]) as required(required_table)
    where to_regclass(required_table) is null;

    if missing_tables is not null then
        raise exception 'Required Peztz tables are missing: %', missing_tables;
    end if;
end $$;

alter table public.users
    alter column password type varchar(255);

create table if not exists public.auth_token (
    id uuid primary key,
    token varchar(255) not null unique,
    user_id uuid not null references public.users(user_id) on delete cascade,
    created_at timestamp not null,
    expires_at timestamp not null
);

create index if not exists idx_auth_token_user_id on public.auth_token(user_id);
create index if not exists idx_auth_token_expires_at on public.auth_token(expires_at);

create sequence if not exists public.access_session_session_id_seq;

alter table public.access_session
    alter column session_id set default nextval('public.access_session_session_id_seq');

alter sequence public.access_session_session_id_seq
    owned by public.access_session.session_id;

alter table public.access_session
    add column if not exists ended_at timestamp with time zone;

create sequence if not exists public.pet_logs_log_id_seq;

alter table public.pet_logs
    alter column log_id set default nextval('public.pet_logs_log_id_seq');

alter sequence public.pet_logs_log_id_seq
    owned by public.pet_logs.log_id;

alter table public.cage
    add column if not exists hospital_id uuid references public.hospitals(hospital_id),
    add column if not exists name varchar(100),
    add column if not exists cage_number varchar(50),
    add column if not exists created_at timestamp;

update public.cage
set created_at = now()
where created_at is null;

alter table public.cage
    alter column created_at set default now(),
    alter column created_at set not null;

create index if not exists idx_cage_hospital_id on public.cage(hospital_id);

-- Camera metadata. A Cage has exactly one camera. The Cage owns the
-- user, current pet, and Raspberry Pi relationships, so they are not
-- duplicated here. RTSP URLs and credentials are not stored here.
create table if not exists public.camera (
    camera_id uuid primary key,
    cage_id uuid not null unique references public.cage(cage_id) on delete restrict,
    name varchar(100) not null,
    status varchar(50) not null,
    stream_status varchar(50) not null,
    rtsp_config_key varchar(255),
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

-- SmartThings device metadata is kept separate from camera and Raspberry Pi
-- metadata. The external SmartThings device ID is mapped to one Cage and is
-- never used as a foreign key directly so a future OAuth migration can keep
-- the internal relationship stable.
create table if not exists public.smartthings_device (
    smartthings_device_mapping_id uuid primary key,
    cage_id uuid not null references public.cage(cage_id) on delete restrict,
    smartthings_device_id varchar(100) not null unique,
    device_type varchar(50) not null,
    label varchar(100),
    battery integer check (battery between 0 and 100),
    online boolean not null default false,
    active boolean not null default true,
    last_seen_at timestamp with time zone,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create index if not exists idx_smartthings_device_cage
    on public.smartthings_device(cage_id, active);

-- Raw readings are retained independently from pet_logs. session_id is
-- nullable so environmental readings are not lost while a cage is empty.
-- Meaningful state transitions for an active session are also written to
-- pet_logs and therefore become available to the existing report pipeline.
create table if not exists public.sensor_reading (
    reading_id bigint generated by default as identity primary key,
    smartthings_device_mapping_id uuid not null
        references public.smartthings_device(smartthings_device_mapping_id) on delete restrict,
    cage_id uuid not null references public.cage(cage_id) on delete restrict,
    session_id bigint references public.access_session(session_id) on delete restrict,
    capability varchar(100) not null,
    attribute varchar(100) not null,
    numeric_value numeric(19,4),
    string_value varchar(255),
    unit varchar(30),
    measured_at timestamp with time zone not null,
    received_at timestamp with time zone not null,
    source varchar(30) not null,
    raw_payload jsonb not null,
    constraint ck_sensor_reading_value check (
        (numeric_value is not null and string_value is null)
        or (numeric_value is null and string_value is not null)
    ),
    constraint uq_sensor_reading_measurement unique (
        smartthings_device_mapping_id, capability, attribute, measured_at
    )
);

create index if not exists idx_sensor_reading_cage_measured_at
    on public.sensor_reading(cage_id, measured_at desc);
create index if not exists idx_sensor_reading_session_measured_at
    on public.sensor_reading(session_id, measured_at desc);
create index if not exists idx_sensor_reading_device_measured_at
    on public.sensor_reading(smartthings_device_mapping_id, measured_at desc);

-- One immutable daily card report per pet and calendar date. Failed AI calls
-- are also recorded so the application can return statistics immediately and
-- retry after a short backoff without creating duplicate rows.
create table if not exists public.daily_report (
    report_id uuid primary key,
    pet_id uuid not null references public."Pets"(pet_id) on delete cascade,
    report_date date not null,
    generation_token uuid,
    status varchar(20) not null,
    total_log_count bigint not null default 0 check (total_log_count >= 0),
    sensor_log_count bigint not null default 0 check (sensor_log_count >= 0),
    average_temperature double precision,
    average_humidity double precision,
    door_open_count bigint not null default 0 check (door_open_count >= 0),
    low_light_count bigint not null default 0 check (low_light_count >= 0),
    content jsonb not null,
    model_name varchar(100),
    error_message varchar(500),
    generated_at timestamp with time zone,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint uq_daily_report_pet_date unique (pet_id, report_date),
    constraint ck_daily_report_status check (status in ('GENERATING', 'READY', 'FAILED')),
    constraint ck_daily_report_generation_token check (
        status <> 'GENERATING' or generation_token is not null
    )
);

alter table public.daily_report
    add column if not exists generation_token uuid;

alter table public.daily_report
    drop constraint if exists ck_daily_report_status,
    drop constraint if exists ck_daily_report_generation_token;

alter table public.daily_report
    add constraint ck_daily_report_status
        check (status in ('GENERATING', 'READY', 'FAILED')),
    add constraint ck_daily_report_generation_token
        check (status <> 'GENERATING' or generation_token is not null);

create index if not exists idx_daily_report_pet_date
    on public.daily_report(pet_id, report_date desc);

-- AI abnormal behavior events reuse the existing pet_logs and pet_videos
-- tables. The event clip URL and thumbnail URL stay in pet_videos; pet_logs
-- identifies the camera and FastAPI retry key. created_at records the
-- actual event detection (start) time supplied by FastAPI. The optional
-- event_ended_at and event_duration_seconds fields record the duration of
-- the behavior itself; the existing pet_videos time columns record the
-- separate evidence-clip interval (including before/after buffer).
alter table public.pet_logs
    add column if not exists camera_id uuid references public.camera(camera_id) on delete restrict,
    add column if not exists external_event_id varchar(100),
    add column if not exists event_ended_at timestamp with time zone,
    add column if not exists event_duration_seconds integer check (event_duration_seconds >= 0);

create unique index if not exists uq_pet_logs_external_event_id
    on public.pet_logs(external_event_id)
    where external_event_id is not null;
create index if not exists idx_pet_logs_camera_created_at
    on public.pet_logs(camera_id, created_at desc);

-- IF NOT EXISTS only checks object names. Verify the columns needed by the
-- Spring entities so a pre-existing, incompatible table cannot pass silently.
do $$
declare
    invalid_columns text;
begin
    with expected(table_name, column_name, udt_name) as (
        values
            ('auth_token', 'id', 'uuid'),
            ('auth_token', 'token', 'varchar'),
            ('auth_token', 'user_id', 'uuid'),
            ('auth_token', 'created_at', 'timestamp'),
            ('auth_token', 'expires_at', 'timestamp'),
            ('access_session', 'ended_at', 'timestamptz'),
            ('cage', 'hospital_id', 'uuid'),
            ('cage', 'name', 'varchar'),
            ('cage', 'cage_number', 'varchar'),
            ('cage', 'created_at', 'timestamp'),
            ('camera', 'camera_id', 'uuid'),
            ('camera', 'cage_id', 'uuid'),
            ('camera', 'name', 'varchar'),
            ('camera', 'status', 'varchar'),
            ('camera', 'stream_status', 'varchar'),
            ('camera', 'rtsp_config_key', 'varchar'),
            ('camera', 'created_at', 'timestamptz'),
            ('camera', 'updated_at', 'timestamptz'),
            ('smartthings_device', 'smartthings_device_mapping_id', 'uuid'),
            ('smartthings_device', 'cage_id', 'uuid'),
            ('smartthings_device', 'smartthings_device_id', 'varchar'),
            ('smartthings_device', 'device_type', 'varchar'),
            ('smartthings_device', 'online', 'bool'),
            ('smartthings_device', 'active', 'bool'),
            ('smartthings_device', 'last_seen_at', 'timestamptz'),
            ('sensor_reading', 'reading_id', 'int8'),
            ('sensor_reading', 'smartthings_device_mapping_id', 'uuid'),
            ('sensor_reading', 'cage_id', 'uuid'),
            ('sensor_reading', 'session_id', 'int8'),
            ('sensor_reading', 'capability', 'varchar'),
            ('sensor_reading', 'attribute', 'varchar'),
            ('sensor_reading', 'numeric_value', 'numeric'),
            ('sensor_reading', 'string_value', 'varchar'),
            ('sensor_reading', 'measured_at', 'timestamptz'),
            ('sensor_reading', 'received_at', 'timestamptz'),
            ('sensor_reading', 'source', 'varchar'),
            ('sensor_reading', 'raw_payload', 'jsonb'),
            ('daily_report', 'report_id', 'uuid'),
            ('daily_report', 'pet_id', 'uuid'),
            ('daily_report', 'report_date', 'date'),
            ('daily_report', 'generation_token', 'uuid'),
            ('daily_report', 'status', 'varchar'),
            ('daily_report', 'total_log_count', 'int8'),
            ('daily_report', 'sensor_log_count', 'int8'),
            ('daily_report', 'average_temperature', 'float8'),
            ('daily_report', 'average_humidity', 'float8'),
            ('daily_report', 'door_open_count', 'int8'),
            ('daily_report', 'low_light_count', 'int8'),
            ('daily_report', 'content', 'jsonb'),
            ('daily_report', 'model_name', 'varchar'),
            ('daily_report', 'error_message', 'varchar'),
            ('daily_report', 'generated_at', 'timestamptz'),
            ('daily_report', 'created_at', 'timestamptz'),
            ('daily_report', 'updated_at', 'timestamptz'),
            ('pet_logs', 'camera_id', 'uuid'),
            ('pet_logs', 'external_event_id', 'varchar'),
            ('pet_logs', 'event_ended_at', 'timestamptz'),
            ('pet_logs', 'event_duration_seconds', 'int4')
    )
    select string_agg(
        format('%I.%I expected %s but found %s',
            expected.table_name,
            expected.column_name,
            expected.udt_name,
            coalesce(actual.udt_name, '<missing>')),
        '; ' order by expected.table_name, expected.column_name)
    into invalid_columns
    from expected
    left join information_schema.columns actual
        on actual.table_schema = 'public'
       and actual.table_name = expected.table_name
       and actual.column_name = expected.column_name
    where actual.column_name is null
       or actual.udt_name <> expected.udt_name;

    if invalid_columns is not null then
        raise exception 'Migration schema validation failed: %', invalid_columns;
    end if;
end $$;

-- Sequence values are adjusted only after schema validation succeeds. Never
-- move an existing sequence backwards when this migration is run again.
select setval(
    'public.access_session_session_id_seq',
    greatest(
        coalesce((select max(session_id) from public.access_session), 0) + 1,
        (select last_value + case when is_called then 1 else 0 end
         from public.access_session_session_id_seq)
    ),
    false
);

select setval(
    'public.pet_logs_log_id_seq',
    greatest(
        coalesce((select max(log_id) from public.pet_logs), 0) + 1,
        (select last_value + case when is_called then 1 else 0 end
         from public.pet_logs_log_id_seq)
    ),
    false
);

-- An older development migration created public.pet_event. It is no longer
-- used, but it might contain data, so do not remove it automatically.
do $$
begin
    if to_regclass('public.pet_event') is not null then
        raise warning 'Legacy table public.pet_event exists; migrate or review its data before removing it';
    end if;
end $$;

commit;
