-- Complete PostgreSQL schema for local Peztz development.
--
-- Run this only against a new local database. Production already owns the
-- original domain tables and must use peztz_domain_migration.sql instead.

begin;

create table if not exists public.hospitals (
    hospital_id uuid primary key,
    name varchar(20) not null,
    phone varchar(20) not null
);

create table if not exists public.users (
    user_id uuid primary key,
    hospital_id uuid references public.hospitals(hospital_id) on delete set null,
    email varchar(50) not null unique,
    password varchar(255) not null,
    name varchar(50) not null,
    role varchar(50) not null
);

create table if not exists public."Pets" (
    pet_id uuid primary key,
    user_id uuid not null references public.users(user_id) on delete cascade,
    name varchar(50) not null,
    pet_breed varchar(50) not null,
    birth_date date,
    medical_note text
);

create index if not exists idx_pets_user_name
    on public."Pets"(user_id, name);

create table if not exists public.raspberrypi (
    device_id uuid primary key,
    mac_address varchar(50),
    last_ip varchar(100),
    is_active varchar(30),
    last_ping time
);

create table if not exists public.cage (
    cage_id uuid primary key,
    hospital_id uuid references public.hospitals(hospital_id) on delete restrict,
    name varchar(100),
    cage_number varchar(50),
    user_id uuid references public.users(user_id) on delete set null,
    current_pet_id uuid references public."Pets"(pet_id) on delete set null,
    access_code varchar(50),
    status varchar(50) not null,
    device_id uuid references public.raspberrypi(device_id) on delete set null,
    created_at timestamp not null default now()
);

create index if not exists idx_cage_hospital_id on public.cage(hospital_id);
create index if not exists idx_cage_user_id on public.cage(user_id);

create table if not exists public.access_session (
    session_id bigint generated by default as identity primary key,
    user_id uuid not null references public.users(user_id) on delete restrict,
    pet_id uuid not null references public."Pets"(pet_id) on delete restrict,
    cage_id uuid not null references public.cage(cage_id) on delete restrict,
    access_code varchar(50) not null,
    status varchar(50) not null,
    created_at timestamp with time zone not null,
    ended_at timestamp with time zone
);

create unique index if not exists uq_access_session_active_code
    on public.access_session(access_code) where status = 'ACTIVE';
create index if not exists idx_access_session_owner_created
    on public.access_session(user_id, created_at desc);
create index if not exists idx_access_session_pet_created
    on public.access_session(pet_id, created_at desc);
create index if not exists idx_access_session_cage_created
    on public.access_session(cage_id, created_at desc);

create table if not exists public.camera (
    camera_id uuid primary key,
    cage_id uuid not null unique references public.cage(cage_id) on delete restrict,
    name varchar(100) not null,
    status varchar(50) not null,
    stream_status varchar(50) not null,
    rtsp_config_key varchar(255),
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table if not exists public.pet_videos (
    video_id bigint generated by default as identity primary key,
    session_id bigint not null references public.access_session(session_id) on delete restrict,
    video_path text,
    thumbnail_path text,
    start_time timestamp with time zone,
    end_time timestamp with time zone,
    duration integer check (duration is null or duration >= 0),
    created_at timestamp with time zone not null
);

create index if not exists idx_pet_videos_session_created
    on public.pet_videos(session_id, created_at desc);

create table if not exists public.pet_logs (
    log_id bigint generated by default as identity primary key,
    session_id bigint not null references public.access_session(session_id) on delete restrict,
    video_id bigint references public.pet_videos(video_id) on delete set null,
    camera_id uuid references public.camera(camera_id) on delete restrict,
    external_event_id varchar(100),
    log_type varchar(50) not null,
    data jsonb not null default '{}'::jsonb,
    created_at timestamp with time zone not null,
    event_ended_at timestamp with time zone,
    event_duration_seconds integer check (event_duration_seconds is null or event_duration_seconds >= 0)
);

create unique index if not exists uq_pet_logs_external_event_id
    on public.pet_logs(external_event_id) where external_event_id is not null;
create index if not exists idx_pet_logs_session_created
    on public.pet_logs(session_id, created_at desc);
create index if not exists idx_pet_logs_camera_created
    on public.pet_logs(camera_id, created_at desc);

create table if not exists public.auth_token (
    id uuid primary key,
    token varchar(255) not null unique,
    user_id uuid not null references public.users(user_id) on delete cascade,
    created_at timestamp not null,
    expires_at timestamp not null
);

create index if not exists idx_auth_token_user_id on public.auth_token(user_id);
create index if not exists idx_auth_token_expires_at on public.auth_token(expires_at);

create table if not exists public.smartthings_device (
    smartthings_device_mapping_id uuid primary key,
    cage_id uuid not null references public.cage(cage_id) on delete restrict,
    smartthings_device_id varchar(100) not null unique,
    device_type varchar(50) not null,
    label varchar(100),
    battery integer check (battery between 0 and 100),
    online boolean not null default false,
    active boolean not null default true,
    last_seen_at timestamp with time zone,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create index if not exists idx_smartthings_device_cage
    on public.smartthings_device(cage_id, active);

create table if not exists public.sensor_reading (
    reading_id bigint generated by default as identity primary key,
    smartthings_device_mapping_id uuid not null
        references public.smartthings_device(smartthings_device_mapping_id) on delete restrict,
    cage_id uuid not null references public.cage(cage_id) on delete restrict,
    session_id bigint references public.access_session(session_id) on delete restrict,
    capability varchar(100) not null,
    attribute varchar(100) not null,
    numeric_value numeric(19,4),
    string_value varchar(255),
    unit varchar(30),
    measured_at timestamp with time zone not null,
    received_at timestamp with time zone not null,
    source varchar(30) not null,
    raw_payload jsonb not null,
    constraint ck_sensor_reading_value check (
        (numeric_value is not null and string_value is null)
        or (numeric_value is null and string_value is not null)
    ),
    constraint uq_sensor_reading_measurement unique (
        smartthings_device_mapping_id, capability, attribute, measured_at
    )
);

create index if not exists idx_sensor_reading_cage_measured_at
    on public.sensor_reading(cage_id, measured_at desc);
create index if not exists idx_sensor_reading_session_measured_at
    on public.sensor_reading(session_id, measured_at desc);
create index if not exists idx_sensor_reading_device_measured_at
    on public.sensor_reading(smartthings_device_mapping_id, measured_at desc);

create table if not exists public.daily_report (
    report_id uuid primary key,
    pet_id uuid not null references public."Pets"(pet_id) on delete cascade,
    report_date date not null,
    generation_token uuid,
    status varchar(20) not null,
    total_log_count bigint not null default 0 check (total_log_count >= 0),
    sensor_log_count bigint not null default 0 check (sensor_log_count >= 0),
    average_temperature double precision,
    average_humidity double precision,
    door_open_count bigint not null default 0 check (door_open_count >= 0),
    low_light_count bigint not null default 0 check (low_light_count >= 0),
    content jsonb not null,
    model_name varchar(100),
    error_message varchar(500),
    generated_at timestamp with time zone,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint uq_daily_report_pet_date unique (pet_id, report_date),
    constraint ck_daily_report_status check (status in ('GENERATING', 'READY', 'FAILED')),
    constraint ck_daily_report_generation_token check (
        status <> 'GENERATING' or generation_token is not null
    )
);

create index if not exists idx_daily_report_pet_date
    on public.daily_report(pet_id, report_date desc);

commit;
