-- SmartThings-only migration for an existing Peztz PostgreSQL database.
--
-- This script does not modify or delete rows in existing domain tables.
-- It only creates the SmartThings mapping/readings tables and their indexes.

begin;

do $$
declare
    missing_tables text;
begin
    select string_agg(required_table, ', ' order by required_table)
    into missing_tables
    from unnest(array[
        'public.cage',
        'public.access_session'
    ]) as required(required_table)
    where to_regclass(required_table) is null;

    if missing_tables is not null then
        raise exception 'Required Peztz tables are missing: %', missing_tables;
    end if;
end $$;

create table if not exists public.smartthings_device (
    smartthings_device_mapping_id uuid primary key,
    cage_id uuid not null references public.cage(cage_id) on delete restrict,
    smartthings_device_id varchar(100) not null unique,
    device_type varchar(50) not null,
    label varchar(100),
    battery integer check (battery between 0 and 100),
    online boolean not null default false,
    active boolean not null default true,
    last_seen_at timestamp with time zone,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create index if not exists idx_smartthings_device_cage
    on public.smartthings_device(cage_id, active);

create table if not exists public.sensor_reading (
    reading_id bigint generated by default as identity primary key,
    smartthings_device_mapping_id uuid not null
        references public.smartthings_device(smartthings_device_mapping_id) on delete restrict,
    cage_id uuid not null references public.cage(cage_id) on delete restrict,
    session_id bigint references public.access_session(session_id) on delete restrict,
    capability varchar(100) not null,
    attribute varchar(100) not null,
    numeric_value numeric(19,4),
    string_value varchar(255),
    unit varchar(30),
    measured_at timestamp with time zone not null,
    received_at timestamp with time zone not null,
    source varchar(30) not null,
    raw_payload jsonb not null,
    constraint ck_sensor_reading_value check (
        (numeric_value is not null and string_value is null)
        or (numeric_value is null and string_value is not null)
    ),
    constraint uq_sensor_reading_measurement unique (
        smartthings_device_mapping_id, capability, attribute, measured_at
    )
);

create index if not exists idx_sensor_reading_cage_measured_at
    on public.sensor_reading(cage_id, measured_at desc);
create index if not exists idx_sensor_reading_session_measured_at
    on public.sensor_reading(session_id, measured_at desc);
create index if not exists idx_sensor_reading_device_measured_at
    on public.sensor_reading(smartthings_device_mapping_id, measured_at desc);

do $$
declare
    invalid_columns text;
begin
    with expected(table_name, column_name, udt_name) as (
        values
            ('smartthings_device', 'smartthings_device_mapping_id', 'uuid'),
            ('smartthings_device', 'cage_id', 'uuid'),
            ('smartthings_device', 'smartthings_device_id', 'varchar'),
            ('smartthings_device', 'device_type', 'varchar'),
            ('smartthings_device', 'online', 'bool'),
            ('smartthings_device', 'active', 'bool'),
            ('smartthings_device', 'last_seen_at', 'timestamptz'),
            ('sensor_reading', 'reading_id', 'int8'),
            ('sensor_reading', 'smartthings_device_mapping_id', 'uuid'),
            ('sensor_reading', 'cage_id', 'uuid'),
            ('sensor_reading', 'session_id', 'int8'),
            ('sensor_reading', 'capability', 'varchar'),
            ('sensor_reading', 'attribute', 'varchar'),
            ('sensor_reading', 'numeric_value', 'numeric'),
            ('sensor_reading', 'string_value', 'varchar'),
            ('sensor_reading', 'measured_at', 'timestamptz'),
            ('sensor_reading', 'received_at', 'timestamptz'),
            ('sensor_reading', 'source', 'varchar'),
            ('sensor_reading', 'raw_payload', 'jsonb')
    )
    select string_agg(
        format('%I.%I expected %s but found %s',
            expected.table_name,
            expected.column_name,
            expected.udt_name,
            coalesce(actual.udt_name, '<missing>')),
        '; ' order by expected.table_name, expected.column_name)
    into invalid_columns
    from expected
    left join information_schema.columns actual
        on actual.table_schema = 'public'
       and actual.table_name = expected.table_name
       and actual.column_name = expected.column_name
    where actual.column_name is null
       or actual.udt_name <> expected.udt_name;

    if invalid_columns is not null then
        raise exception 'SmartThings migration schema validation failed: %', invalid_columns;
    end if;
end $$;

commit;
