spring.application.name=spring-server

spring.datasource.url=jdbc:postgresql://${DB_HOST:34.50.7.78}:${DB_PORT:5432}/${DB_NAME:PEZTZ}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true